### ISSUE TITLE
504 Gateway Timed Out on large expression

### ISSUE THREAD

**Issue by seanmcilvenna** [IHTSDO/sct-snapshot-rest-api#12]
I am getting a 504 gateway timed out error when I run a large expression:
< 404684003 | Clinical finding (finding) | OR < 243796009 | Situation with explicit cont ext (situation) |
What can I do to resolve this?

**Comment by rorydavidson** [comment]
A very long response to this, but we do not recommend using the expression functionality on this codebase for now due to performance concerns. 
For a server specifically to run expressions, please look to use [the SNOMED Query Server](https://github.com/IHTSDO/snomed-query-service)
