### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mbonda** [IHTSDO/sct-snapshot-rest-api#21]
For the installation, first i have to install mean? how ?

**Comment by rorydavidson** [comment]
You can find out more information on MEAN and how to install here - http://mean.io/

**Comment by mbonda** [comment]
And the installation of snomed rest, is in the same directory of mean ?

**Comment by rorydavidson** [comment]
this repository runs on nodejs, so it can run in any directory, installed and run as in the readme
