### ISSUE TITLE
Schema Documentation

### ISSUE THREAD

**Issue by ianfieldarsclinica** [IHTSDO/sct-snapshot-rest-api#26]
We've loaded the latest snapshot into mongodb with the structure:

db: test
collections:
-   concepts
-   descriptions
-   relationships

The documentation doesn't provide any information on whether this is correct.  The code seems to imply that "edition" is the mongo db name and "release" is a collection..?

Clarification needed.

**Comment by rorydavidson** [comment]
This is correct. The edition, i.e. en-edition, is the name of the mongo dB, and the release is the name used with the relevant collections. What is the issue you're experiencing?

**Comment by ianfieldarsclinica** [comment]
I think our issue is that we used a different script to load our data into mongodb.  This one: https://simopr.wordpress.com/2016/02/22/how-to-load-snomed-ct-into-mongodb-using-nodejs/

I was hoping that the structure would be similar.

We initially had some issues with https://github.com/IHTSDO/rf2-to-json-conversion (for one thing, the apt-get release is currently broken due to a date issue - https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1649086)

I've now compiled that via Maven and am attempting to recreate the DB.  It's a huge resource hog on the little linux box we dedicated to this...  Seems to be stuck about halfway in.  I'll update here if/when it loads.

Thanks for your response.

**Comment by rorydavidson** [comment]
I was unaware of that blog entry but it doesn't look like it is built upon the work here. 
There is a complied binary of the rf2 to json conversion here - https://github.com/IHTSDO/rf2-to-json-conversion/releases/tag/v1.2.

We generally build the json files on local machines as they tend to have more power than the small Linux servers we also use. We then transfer the resulting json files to the server and load using the import.sh script in the rf2 to json repo scripts directory.

**Comment by ianfieldarsclinica** [comment]
Got it - thank you!  I think you've given us what we need.
