### ISSUE TITLE
Reference Error - getTime is not defined when starting the app.js

### ISSUE THREAD

**Issue by mckanthcdoc** [IHTSDO/sct-snapshot-rest-api#30]
[root@server sct-snapshot-rest-api]# node app.js &
[3] 12317
[root@server sct-snapshot-rest-api]# Master cluster setting up 1 workers...
(node:12317) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
/root/nodeserver/sct-snapshot-rest-api/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^

ReferenceError: getTime is not defined
    at /root/nodeserver/sct-snapshot-rest-api/routes/server.js:12:22
    at connectCallback (/root/nodeserver/sct-snapshot-rest-api/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /root/nodeserver/sct-snapshot-rest-api/node_modules/mongodb/lib/mongo_client.js:418:11
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:12331) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by 009topersky** [comment]
Try this to add on your server.js

var getTime = function() {
  var currentdate = new Date();
  var datetime =
    'Last Sync: ' +
    currentdate.getDate() +
    '/' +
    (currentdate.getMonth() + 1) +
    '/' +
    currentdate.getFullYear() +
    ' @ ' +
    currentdate.getHours() +
    ':' +
    currentdate.getMinutes() +
    ':' +
    currentdate.getSeconds();
  return datetime;
};

**Comment by mckanthcdoc** [comment]
Sorry it was an error with MongoDB instance not available. It got resolved after the MongoDB instance was up and running. Thanks for your support
