### ISSUE TITLE
Dependent repository (rf2-to-json-conversion v1.3) fails to convert RF2 to JSON

### ISSUE THREAD

**Issue by priyaranjan-tokachichu** [IHTSDO/sct-snapshot-rest-api#35]
Trying to use the latest version (v1.3 Development) of the rf2-to-json-conversion in order to use the v2 API. But, it fails to convert the RF2 SNOMED file to JSON. There are no problems with v1.2 in conversion.
![2018-04-22 03_06_10-administrator_ windows powershell](https://user-images.githubusercontent.com/23316700/39092498-169e4620-45dd-11e8-8f8a-6ce0cf474190.png)

**Comment by rorydavidson** [comment]
Have you built that version yourself or used the available released v1.3 of the rf2-to-json-conversion jar? And what have config have you used?

**Comment by priyaranjan-tokachichu** [comment]
I tried both. I used "java -Xmx8g -jar rf2-to-json-conversion-1.3-jar-with-dependencies.jar config.xml" as in the documentation. It was successful with the 1.2 release, but not with 1.3 pre-release.
I did not add any other configuration options. My machine is Windows 10.

**Comment by rorydavidson** [comment]
Could you please paste in your config.xml. I don't have access to a Windows machine, but I can't replicate the issues with the v1.3 pre-release jar on anything else.

**Comment by priyaranjan-tokachichu** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<config>
    <processInMemory>true</processInMemory>
    <defaultTermLangCode>en</defaultTermLangCode>
    <defaultTermDescriptionType>900000000000003001</defaultTermDescriptionType>
    <defaultTermLanguageRefset>900000000000509007</defaultTermLanguageRefset>
    <normalizeTextIndex>true</normalizeTextIndex>
    <createCompleteConceptsFile>false</createCompleteConceptsFile>
    <editionName>Company Edition</editionName>
    <databaseName>company-edition</databaseName>
    <effectiveTime>20180131</effectiveTime>
    <expirationTime>20190131</expirationTime>
    <outputFolder>company-json</outputFolder>
    <foldersBaselineLoad>
        <folder>Snapshot</folder>
    </foldersBaselineLoad>
    <modulesToIgnoreBaselineLoad>
    </modulesToIgnoreBaselineLoad>
    <foldersExtensionLoad>
    </foldersExtensionLoad>
    <modulesToIgnoreExtensionLoad>
    </modulesToIgnoreExtensionLoad>
</config>`

**Comment by priyaranjan-tokachichu** [comment]
It could be a windows specific issue. But, why is v1.2 working but not v1.3? That is inconsistent if that is a windows specific issue.

**Comment by rorydavidson** [comment]
I couldn't say (I don't have access to a Windows machine to try). I'd recommend building the develop branch of the https://github.com/IHTSDO/rf2-to-json-conversion/ repo and see if the resulting jar file works, or creating the output directory beforehand to check if it is that.

**Comment by priyaranjan-tokachichu** [comment]
I did build the jar file from the development branch and tried with the same result. I will try to create the output directory beforehand to see if that is going to change anything. I tried the generation of the json multiple times, which means that the directory already exists after the first try. But, I will try as you said and report back.

**Comment by priyaranjan-tokachichu** [comment]
Just tried. Got the same error at the end.
```
Default Terms computation completed
Exception in thread "main" java.lang.NullPointerException
        at org.ihtsdo.json.TransformerDiskBased.completeModuleAndDefStatus(TransformerDiskBased.java:400)
        at org.ihtsdo.json.TransformerDiskBased.convert(TransformerDiskBased.java:198)
        at org.ihtsdo.json.runners.ConfigRunner.execute(ConfigRunner.java:131)
        at org.ihtsdo.json.runners.ConfigRunner.main(ConfigRunner.java:31)
```

**Comment by rorydavidson** [comment]
Which version & edition of SNOMED CT are you trying to convert?

**Comment by priyaranjan-tokachichu** [comment]
This is an extension based on the SNOMED US Edition. After I generated the RF2 file, the SNOMED version was updated. So, I don't have that information handy, but I will be able to get it if that is important. In the meantime, I will generate another extension snapshot from the latest build to see if that is the issue. I will also try cygwin on windows to see if that makes any difference.

**Comment by priyaranjan-tokachichu** [comment]
Latest export of the extension failed. This RF2 file includes just the snapshot of the extension, but not the entire edition. I use this to test the API, and when everything looks good I switch over to the edition. It worked so far with previous releases. The SNOMED US edition we used is 20180301.

**Comment by rorydavidson** [comment]
This is more likely to be be the reason. Running this on an extension without the required edition is likely to fail. v1.3 of the conversion adds a bit more checking into the process which may explain why it doesn't fail for v1.2. You can include the US edition and then the extension in the same build.

**Comment by priyaranjan-tokachichu** [comment]
I will try that and report back.

**Comment by priyaranjan-tokachichu** [comment]
Perfect! Thank you! It worked on the Edition. I am closing the issue.
